version: 1.0.{build}
image: Visual Studio 2017

# branches to build
branches:
  # whitelist
  only:
  - master

  # blacklist
  except:
  - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
# skip_non_tags: true

# set clone depth
clone_depth: 5                      # clone entire repository history if not defined

# environment:
  # matrix:
  #- Platform: net20
  #- Platform: net40
  # - Platform: net45
  #- Platform: sl5
  # - Platform: netstandard1.3
  #- Platform: monoandroid2.3
  #- Platform: xamarinios1.0

# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config

install:
  - nuget restore Test.sln

build:
  project: Test.sln

after_test:
  - cmd: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:MSTest.exe -targetargs:"/testcontainer:Test/bin/debug/Test.dll" -output:coverage.xml
  - cmd: packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml -r Eb6EkSCbTNWwxd7s6Vf6xcZaYXNc8z1HE